# Generated by Django 5.1.1 on 2024-09-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
