# Generated by Django 5.1.1 on 2024-09-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_delete_blogpost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта"),
                    (
                        "can_change_product_description",
                        "Может менять описание любого продукта",
                    ),
                    (
                        "can_change_product_category",
                        "Может менять категорию любого продукта",
                    ),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
